version: "3.7"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    # volumes:
    #   - ./middleware/pgadmin/data:/var/lib/pgadmin
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: zHbK7RubeqTU
      TZ: "Asia/Tokyo"


  pgsql:
    hostname: pgsql
    build:
      context: ./middleware/pgsql
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./middleware/pgsql/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: system
      POSTGRES_USER: system
      POSTGRES_DB: tkdb
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      POSTGRES_HOST_AUTH_METHOD: trust
      TZ: "Asia/Tokyo"
    # command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on

  grafana:
    hostname: grafana
    image: docker.io/bitnami/grafana:7-debian-10
    restart: always
    user: "1000"
    ports:
      - 3000:3000
    environment:
      TZ: "Asia/Tokyo"
      GF_SECURITY_ADMIN_PASSWORD: qjNY6eY4zNjK
    volumes:
      - ./middleware/grafana/data:/opt/bitnami/grafana/data
      - ./middleware/grafana/etc/grafana:/etc/grafana
      - ./middleware/grafana/usr/share/grafana:/usr/share/grafana

  driver:
    build:
      context: ./driver
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    environment:
      TZ: Asia/Tokyo
      DOCKER: 1
    tty: true
    volumes:
      - ./driver:/var/driver
    command: python3 /var/driver/app.py

  cp:
    build:
      context: ./control-panel
      dockerfile: Dockerfile
    volumes:
      - ./control-panel:/root/control-panel
      - ./middleware/nginx/static:/var/www/static
    ports:
      - 28080:8080
    tty: true
    # command: yarn add && yarn serve

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    environment:
      TZ: Asia/Tokyo
    volumes:
      - ./middleware/nginx/static:/var/www/static
      - ./middleware/nginx/conf.d:/etc/nginx/conf.d
