version: 2.1
jobs:
  deploy-web-db:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
          - ${KEY_FINGERPRINT}
      - run: "ssh ${USER_NAME}@${HOST_NAME} -p ${SSH_PORT} \
      \"ssh gn-sv-08 && \
      cd ~/Git/TempKeeper && git pull && sudo systemctl restart TempKeeper.service \""

  deploy-driver:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
          - ${KEY_FINGERPRINT}
      - run: "ssh ${USER_NAME}@${HOST_NAME} -p ${SSH_PORT} \
      \"ssh gn-sv-11 && \
      cd ~/TempKeeper && git pull && sudo systemctl restart TempKeeperAdminService.service \""

  deploy-viewer:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
          - ${KEY_FINGERPRINT}
      - run: "ssh ${USER_NAME}@${HOST_NAME} -p ${SSH_PORT} \
      \"ssh gn-cl-05 && \
      cd ~/TempKeeper && git pull && sudo systemctl restart TempKeeperViewer.service \""

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-web-db:
          filters:
            branches:
              only: main
      - deploy-driver:
          filters:
            branches:
              only: main
      - deploy-viewer:
          filters:
            branches:
              only: main
