version: 2.1
jobs:
  deploy-web-db:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
          - ${RELAY_FINGERPRINT}
      - run:
          command: "ssh -o StrictHostKeyChecking=no ${RELAY_USER}@${RELAY_HOST} -p ${RELAY_SSH_PORT} \
          \"ssh gn-sv-08 \
          'cd ~/Git/TempKeeper && git pull && sudo systemctl restart TempKeeper.service'\""
          no_output_timeout: 10m

  deploy-driver:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
          - ${RELAY_FINGERPRINT}
      - run:
          command: "ssh -o StrictHostKeyChecking=no ${RELAY_USER}@${RELAY_HOST} -p ${RELAY_SSH_PORT} \
          \"ssh gn-sv-11 \
          'cd ~/TempKeeper && git pull && sudo systemctl restart TempKeeperAdminService.service'\""
          no_output_timeout: 10m

  deploy-viewer:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
          - ${RELAY_FINGERPRINT}
      - run:
          command: "ssh -o StrictHostKeyChecking=no ${RELAY_USER}@${RELAY_HOST} -p ${RELAY_SSH_PORT} \
          \"ssh gn-cl-14 \
          'sleep 15s && cd ~/TempKeeper && git pull && sudo systemctl restart TempKeeperViewer.service'\""
          no_output_timeout: 10m

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-web-db:
          filters:
            branches:
              only: main
      - deploy-driver:
          filters:
            branches:
              only: main
      - deploy-viewer:
          requires:
            - deploy-web-db
            - deploy-driver
          filters:
            branches:
              only: main
