{
 "title": "小鳥ケージ状態",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "現在の温度(℃)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  t.sent_at AS \"time\",\n  n.location_name AS \"metric\",\n  t.temp as temperature\nFROM temperature as t\nLEFT JOIN node AS n ON n.sensor_mac = t.mac\nWHERE\n  $__timeFilter(sent_at)\nORDER BY n.id ASC, time ASC"
    }
   ]
  },
  {
   "title": "設定温度(℃)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  t.sent_at AS \"time\",\n  n.location_name AS \"metric\",\n  n.preset_temp as preset\nFROM temperature as t\nLEFT JOIN node AS n ON n.sensor_mac = t.mac\nWHERE\n  $__timeFilter(sent_at)\nORDER BY n.id ASC, time ASC"
    }
   ]
  },
  {
   "title": "ヒーター",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  p.sent_at AS \"time\",\n  n.location_name AS \"metric\",\n  p.status as status\nFROM plug_state as p\nINNER JOIN node AS n ON n.plug_mac = p.mac\nWHERE\n  $__timeFilter(sent_at)\nORDER BY n.id ASC, time DESC",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "温度(℃)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  t.sent_at AS \"time\",\n  n.location_name AS \"metric\",\n  t.temp as temperature\nFROM temperature as t\nINNER JOIN node AS n ON n.sensor_mac = t.mac\nWHERE\n  $__timeFilter(sent_at)\nORDER BY n.id ASC, time DESC"
    }
   ]
  },
  {
   "title": "湿度(%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  t.sent_at AS \"time\",\n  n.location_name AS \"metric\",\n  t.humidity as humidity\nFROM temperature as t\nINNER JOIN node AS n ON n.sensor_mac = t.mac\nWHERE\n  $__timeFilter(sent_at)\nORDER BY n.id ASC, time DESC"
    }
   ]
  }
 ]
}