{
 "title": "小鳥ケージ状態",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "状態サマリ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "現在の温度(℃)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  t.sent_at AS \"time\",\n  n.location_name AS \"metric\",\n  t.temp as temperature\nFROM temperature as t\nLEFT JOIN node AS n ON n.sensor_mac = t.mac\nWHERE\n  $__timeFilter(sent_at)\nORDER BY n.id ASC, time ASC"
    }
   ]
  },
  {
   "title": "温度(℃)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius", "label": "温度(℃)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  t.sent_at AS \"time\",\n  n.location_name AS \"metric\",\n  t.temp as temperature\nFROM temperature as t\nINNER JOIN node AS n ON n.sensor_mac = t.mac\nWHERE\n  $__timeFilter(sent_at)\nORDER BY n.id ASC, time DESC"
    }
   ]
  },
  {
   "title": "ヒーター",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "rawSql": "SELECT\n  p.sent_at AS \"time\",\n  n.location_name AS \"metric\",\n  p.status as status\nFROM plug_state as p\nINNER JOIN node AS n ON n.plug_mac = p.mac\nWHERE\n  $__timeFilter(sent_at)\nORDER BY n.id ASC, time DESC",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "湿度(%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent", "label": "湿度(%)" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  t.sent_at AS \"time\",\n  n.location_name AS \"metric\",\n  t.humidity as humidity\nFROM temperature as t\nINNER JOIN node AS n ON n.sensor_mac = t.mac\nWHERE\n  $__timeFilter(sent_at)\nORDER BY n.id ASC, time DESC"
    }
   ]
  }
 ]
}